name = "schoolopedia-api"
main = "workers/api/src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

routes = [
  { pattern = "api.schoolopedia.com", custom_domain = true }
]

[vars]
ENVIRONMENT = "development"

[[d1_databases]]
binding = "DB"
database_name = "schoolopedia-db"
database_id = "6741d7ad-17d9-4142-a02a-9e77b33f0ad3"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "KV"
id = "4970ba5253824a28895b5f2467eca85f"

[triggers]
crons = ["*/15 * * * *"]
